apiVersion: elemental.cattle.io/v1beta1
kind: ManagedOSVersionChannel
metadata:
  name: elemental-versions
  namespace: fleet-default
spec:
  options:
    args:
      - github
    command:
      - /usr/bin/upgradechannel-discovery
    envs:
      - name: REPOSITORY
        value: rancher/elemental
      - name: IMAGE_PREFIX
        value: quay.io/costoolkit/elemental
    image: quay.io/costoolkit/upgradechannel-discovery:v0.3-4b83dbe
  type: custom