name: Test build iso from simple script

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Build iso from script
        shell: bash
        run: |
          cat elemental-iso-build | bash