name: Test build iso from simple script

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sudo curl docker.io
      - name: Build iso from script
        run: |
          # Just a simple run to test the build script, no need to upload the generated iso!
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/rancher/elemental/master/elemental-iso-build)"
