name: Test build iso from simple script

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y mkisofs
      - name: Build iso from script
        run: |
          # Just a simple run to test the build script, no need to upload the generated iso!
          echo "TEST" > config.yaml
          curl -fsSL https://raw.githubusercontent.com/rancher/elemental/main/elemental-iso-build -o elemental-iso-build
          chmod +x ./elemental-iso-build
          ./elemental-iso-build config.yaml
      - name: Check config was inserted
        run: |
          ISO=$(find . -name "elemental-*.iso" -print)
          # Extract config and check against our config
          isoinfo -x /livecd-cloud-config.yaml -R -i $ISO > livecd-cloud-config.yaml
          # This checks that the files are the same content
          cmp config.yaml livecd-cloud-config.yaml
      - name: Basic sanity checks for ISO
        run: |
          ISO=$(find . -name "elemental-*.iso" -print)
          # Check it has eltorito
          isoinfo -d -i $ISO|grep -q Eltorito
          # check bootable flag
          isoinfo -d -i $ISO|grep -q bootable        
