name: build-ci

on:
  pull_request:

jobs:
  build-all-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Export tag
        id: export_tag
        run: |
          git describe --abbrev=0 --tags
          TAG=`git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0"`
          echo "::set-output name=elemental_tag::$TAG"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y genisoimage
      - name: Build image
        run: |
          make build
          make dump_image
      - name: Build iso
        run: |
          make iso
      - name: Build ipxe artifacts
        run: |
          make extract_kernel_init_squash
          make ipxe
      - name: Upload iPXE
        uses: actions/upload-artifact@v3
        with:
          name: ipxe-artifacts
          path: |
            build/*-kernel
            build/*-initrd
            build/*.squashfs
            build/*.ipxe
  e2e-tests:
    runs-on: kvm-host
    needs: build-all-artifacts
    container:
      image: opensuse/leap:latest
      env:
        TIMEOUT_SCALE: 2
        CLUSTER_NAME: cluster-k3s
        CLUSTER_NS: fleet-default
        INSTALL_K3S_VERSION: v1.23.9+k3s1
        INSTALL_K3S_SKIP_ENABLE: true
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        ARCH: amd64
      options: --privileged
    steps:
      - name: Install dependencies
        run: zypper -n in -l qemu-kvm libvirt virt-install curl helm git-core tar make gcc
      - name: Be sure to remove all previous data from worker ♻
        run: rm -rf ./*
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.18'
      - name: Download iPXE
        uses: actions/download-artifact@v3
        with:
          name: ipxe-artifacts
          path: ./
      - name: E2E - Clean local Helm repositorie
        run: |
          # Clean Helm repo
          HELM_REPO=$(helm repo list 2>/dev/null | awk '(NR>1) { print $1 }')
          [[ -n "${HELM_REPO}" ]] && helm repo remove ${HELM_REPO} || true
      - name: E2E - Install Rancher
        run: cd tests && make e2e-install-rancher
      - name: E2E - Bootstrap node 1 with current build
        env:
          VM_INDEX: 1
        run: cd tests && make e2e-bootstrap-node
      - name: E2E - Bootstrap node 2 with current build
        env:
          VM_INDEX: 2
        run: cd tests && make e2e-bootstrap-node
  cleanup:
    runs-on: kvm-host
    if: always()
    needs: e2e-tests
    steps:
      - name: Release space from worker ♻
        run: sudo docker system prune -f -a --volumes