name: Test inject iso from simple script - PR edition

on:
  pull_request:
    paths:
      - .github/elemental-iso-add-registration
      - .github/workflows/build-iso-inject-pr.yaml

jobs:
  elemental-iso-build:
    env:
      TAG: ${{ github.SHA }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: ["amd64"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Docker on MacOS and start Colima
        if: runner.os == 'macOS'
        run: |
          # NOTE: we're not using docker-practice/actions-setup-docker because of issues with it
          brew install docker
          # Docker engine is not available because of licensing issue
          # See https://github.com/actions/runner-images/issues/2150#issuecomment-737125967
          # Alternative Colima is part of the github macOS runner, start it for Docker
          colima start
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Install deps (${{ runner.os }})
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y mkisofs
          elif [[ "${{ runner.os }}" == "macOS" ]]; then
            brew install cdrtools
          fi
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build iso from script
        env:
          ARCH: ${{ matrix.arch }}
        run: |
          # Just a simple run to test the build script, no need to upload the generated iso!
          echo "TEST" > config.yaml
          chmod +x .github/elemental-iso-add-registration
          .github/elemental-iso-add-registration config.yaml
      - name: Check config was inserted
        run: |
          ISO=$(find . -name "elemental-*.iso" -print)
          # Extract config and check against our config
          isoinfo -x /livecd-cloud-config.yaml -R -i $ISO > livecd-cloud-config.yaml
          # This checks that the files are the same content
          cmp config.yaml livecd-cloud-config.yaml
      - name: Basic sanity checks for ISO
        run: |
          ISO=$(find . -name "elemental-*.iso" -print)
          # Check it has eltorito
          isoinfo -d -i $ISO | grep -q Eltorito
          # check bootable flag
          isoinfo -d -i $ISO | grep -q bootable
