# This workflow calls the master E2E workflow with custom variables
name: CLI-K3s-Hardened-Rancher_Latest

on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  cli:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
      pat_token: ${{ secrets.SELF_HOSTED_RUNNER_PAT_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      test_description: "CI - CLI - Parallel - Deployment test with Hardened K3s"
      cert-manager_version: v1.11.1
      cluster_name: cluster-k3s
      cluster_type: hardened
      k8s_version_to_provision: v1.25.7+k3s1
      node_number: 3
      rancher_version: latest/devel
