name: docs
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install mkdocs-markdownextradata-plugin
      - name: Deploy docs
        if: ${{ github.event_name == 'push' }}
        run: mkdocs gh-deploy --force --strict
      - name: Build docs
        if: ${{ github.event_name == 'pull_request' }}
        run: mkdocs build --strict
