name: docs

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install mkdocs-material mkdocs-markdownextradata-plugin
      - name: Deploy docs
        if: ${{ github.event_name == 'push' }}
        run: mkdocs gh-deploy --force --strict
      - name: Build docs
        if: ${{ github.event_name == 'pull_request' }}
        run: mkdocs build --strict
