# This workflow calls the master E2E workflow with custom variables
name: RKE2-E2E-Latest_RM

# This worflow is scheduled *after* build-ci to be sure that we have
# the lastest version built. The scheduling is also to avoid running
# the worklow on each push on main.
on:
  schedule:
    - cron: '0 1 * * *'

jobs:
  rke2:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
      pat_token: ${{ secrets.SELF_HOSTED_RUNNER_PAT_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      test_description: "CI - E2E CLI - Parallel - Deployment test with Standard RKE2"
      ca_type: private
      cluster_name: cluster-rke2
      k8s_version_to_provision: v1.24.8+rke2r1
      rancher_channel: latest
      rancher_version: devel
