# This workflow calls the master E2E workflow with custom variables
name: Elemental End-To-End tests with Rancher Manager

on:
  workflow_run:
    workflows:
      - build-ci
    branches:
      - main
    types:
      - completed

concurrency:
  group: e2e-test-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  k3s:
    uses: ./.github/workflows/master-e2e.yaml
    with:
      runner: kvm-host
      cluster_name: cluster-k3s
      k8s_version_to_provision: v1.23.10+k3s1
  rke2:
    uses: ./.github/workflows/master-e2e.yaml
    with:
      runner: kvm-host
      cluster_name: cluster-rke2
      k8s_version_to_provision: v1.23.10+rke2r1
