name: e2e

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Export tag
        id: export_tag
        run: |
          git describe --abbrev=0 --tags
          TAG=`git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0"`
          echo "::set-output name=elemental_tag::$TAG"
      - name: Build iso
        run:
          make iso