name: Build elemental docker image

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO: ttl.sh/elemental-ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Export tag
        id: export_tag
        run: |
          git describe --abbrev=0 --tags
          TAG=`git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0"`
          echo "::set-output name=elemental_tag::$TAG"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.REPO }}
          tags: |
            type=semver,pattern=v{{version}}
            type=sha,format=short,prefix=${{ steps.export_tag.outputs.elemental_tag }}-
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          # cache into GitHub actions cache, nice
          cache-from: type=gha
          cache-to: type=gha,mode=max
          target: default
          file: Dockerfile.image
          build-args: |
            IMAGE_TAG=${{ steps.meta.outputs.version }}
            IMAGE_COMMIT=${{ github.sha }}
            IMAGE_REPO=${{ env.REPO }}