name: Manual Integration tests
on:
  workflow_dispatch:
    inputs:
      box-image:
        required: false
        default: https://github.com/rancher/os2/releases/download/v0.1.0-alpha12/rancheros-v0.1.0-alpha12-amd64.box
        type: string
        description: QEMU .box image to test
      iso-image:
        required: false
        default: https://github.com/rancher/os2/releases/download/v0.1.0-alpha12/rancheros-v0.1.0-alpha12-amd64.iso
        type: string
        description: ISO image to test
jobs:

  tests-vbox:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.17'
      - name: Install deps
        run: |
          brew install cdrtools jq
      - name: Run tests
        env:
          BOX_URL: ${{ github.event.inputs.box-image }}
          ISO_URL: ${{ github.event.inputs.iso-image }}
        run: |
          curl -L ${ISO_URL:-https://github.com/rancher/os2/releases/download/v0.1.0-alpha12/rancheros-v0.1.0-alpha12-amd64.iso} -o ros.iso
          # curl -L ${BOX_URL:-https://github.com/rancher/os2/releases/download/v0.1.0-alpha12/rancheros-v0.1.0-alpha12-amd64.box} -o ros.box
          export COS_HOST=127.0.0.1:2222
          export ISO=$PWD/ros.iso
          make deps
          cd tests && make vbox-tests
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ros-vbox.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
            go-version: '^1.17'
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get remove -y apparmor*
          sudo apt-get install -y qemu-system-x86 make libvirt-daemon-system bridge-utils ovmf curl
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install vagrant
          sudo apt-get install -y qemu libvirt-daemon-system libvirt-clients ebtables dnsmasq-base
          sudo apt-get install -y libxslt-dev libxml2-dev libvirt-dev zlib1g-dev ruby-dev
          sudo apt-get install -y libguestfs-tools gcc
          vagrant plugin install vagrant-libvirt

      - name: Prepare libvirt
        run: |
          # Create bridge conf
          sudo mkdir -p /etc/qemu/
          echo "allow all" | sudo tee -a /etc/qemu/bridge.conf
          sudo chmod u+r /etc/qemu/bridge.conf
          sudo chmod u+s $(find /usr/ -name qemu-bridge-helper -print -quit|xargs)

          # sudo /usr/sbin/libvirtd &
          # sleep 5

          # Set a static ip for our VM
          sudo virsh net-update default add ip-dhcp-host "<host mac='52:54:00:00:00:01' name='jojo' ip='192.168.122.50' />" --live --config  || true
      - name: Run tests
        env:
          BOX_URL: ${{ github.event.inputs.box-image }}
        run: |
          curl -L ${BOX_URL:-https://github.com/rancher/os2/releases/download/v0.1.0-alpha12/rancheros-v0.1.0-alpha12-amd64.box} -o ros.box
          export BOX=$PWD/ros.box
          make integration-tests
      - name: Release space from worker ♻
        if: always()
        run: |
          sudo rm -rf build || true
          sudo rm -rf bin || true
          sudo rm -rf dist || true
          cd tests && make clean || true
          docker system prune -f -a --volumes || true
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: ros-libvirt.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn