name: Integration tests

on:
  workflow_run:
    workflows:
      - build-ci
    types:
      - completed
  pull_request:

concurrency:
  group: integration-tests-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true

env:
  REPO: ttl.sh/elemental-ci
jobs:
  tests-installer:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.18'
      - name: Install dependencies
        run: brew install cdrtools jq
      - name: Wait for build
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-all-artifacts
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 1800
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          #workflow: ${{ github.event.workflow_run.workflow_id }}
          #workflow_conclusion: success
          workflow: build-ci.yaml
          run_id: ${{ github.event.workflow_run.id }}
          name: iso-image
          # Force the path, this is a security hint!
          path: ./
      - name: Run tests
        run: |
          GIT_TAG=$(git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0")
          GIT_COMMIT_SHORT=$(git rev-parse --short HEAD)
          export CONTAINER_IMAGE=${REPO}:${GIT_TAG}-${GIT_COMMIT_SHORT}
          export COS_HOST=127.0.0.1:2222
          export ISO=$PWD/$(ls elemental-*.iso 2>/dev/null)
          cd tests && make installer-tests
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: vbox.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
      - name: Release space from worker ♻
        if: always()
        run: |
          cd tests && make clean || true
          sudo rm -rf build bin dist || true
  tests-vbox:
    runs-on: macos-12
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Export tag
        id: export_tag
        run: |
          git describe --abbrev=0 --tags
          TAG=`git describe --abbrev=0 --tags 2>/dev/null || echo "v0.0.0"`
          echo "::set-output name=elemental_tag::$TAG"
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.18'
      - name: Install dependencies
        run: brew install cdrtools jq
      - name: Wait for build
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: build-all-artifacts
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          timeoutSeconds: 1800
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          #workflow: ${{ github.event.workflow_run.workflow_id }}
          #workflow_conclusion: success
          workflow: build-ci.yaml
          run_id: ${{ github.event.workflow_run.id }}
          name: iso-image
          # Force the path, this is a security hint!
          path: ./
      - name: Run tests
        run: |
          export COS_HOST=127.0.0.1:2222
          export ISO=$PWD/$(ls elemental-*.iso 2>/dev/null)
          cd tests && make vbox-tests
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: vbox.logs.zip
          path: tests/**/logs/*
          if-no-files-found: warn
      - name: Release space from worker ♻
        if: always()
        run: |
          cd tests && make clean || true
          sudo rm -rf build bin dist || true
