# This workflow is for testing Qase reporting
# It will be deleted after testing
name: QASE-reporting-test
on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_autocomplete_run:
        description: 'Qase Run autocomplete'
        required: true
env:
    QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
    QASE_REPORT: ${{ inputs.qase_report }}
    QASE_PROJECT_CODE: ${{ inputs.qase_project_code }}
    QASE_RUN_ID: ${{ inputs.qase_run_id }}
    QASE_COMPLETE_RUN_AFTER_SUBMIT: ${{ inputs.qase_autocomplete_run }}
    QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}

jobs:
  build-php:
    runs-on: ubuntu-latest
    steps:
      - uses: qase-tms/qase-link-run@main
    env:
      QASE_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  Test-qase-reporting:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
