name: Release

on:
  push:
   tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      DOCKER_REGISTRY: quay.io
      REPO: quay.io/costoolkit/os2
    steps:
      - uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - run: |
              make ci
      - name: Release
        uses: rancher-sandbox/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/artifacts/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PARALLELISM: "1"
      - name: Release space from worker ♻
        if: always()
        run: |
          sudo rm -rf build || true
          sudo rm -rf bin || true
          sudo rm -rf dist || true
          docker system prune -f -a --volumes || true