name: Release

on:
  push:
   tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Artifacts
        run: |
          # Replace default TAG with our tag
          sed "s/\${TAG:-main}/${{ github.ref_name }}/g" .github/elemental-iso-build
          mkdir release
          cp .github/elemental-iso-build release/elemental-iso-build
          chmod +x release/elemental-iso-build
      - name: Release
        uses: rancher-sandbox/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: release/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PARALLELISM: "1"
      - name: Release space from worker ♻
        if: always()
        run: |
          sudo rm -rf build bin dist || true
          docker system prune -f -a --volumes || true
