name: Static Analysis
on:
  push:
concurrency:
  group: static-analysis-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: true
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Analysis
      uses: golangci/golangci-lint-action@v3
      with:
        args: -v