# This workflow calls the master E2E workflow with custom variables
name: RKE2 - Elemental UI End-To-End tests with Rancher Manager

on:
  workflow_dispatch:
    inputs:
      rancher_channel:
        description: Rancher Manager channel to use for installation (alpha/latest/stable)
        default: latest
        type: string
      rancher_version:
        description: Rancher Manager version to use for installation (fixed version or latest)
        default: devel
        type: string
      upgrade_operator:
        description: URL to elemental-operator version to upgrade to
        type: string
  schedule:
    - cron: '0 4 * * *'

jobs:
  ui-rke2:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
      pat_token: ${{ secrets.SELF_HOSTED_RUNNER_PAT_TOKEN }}
      slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
    with:
      #ui_account: user
      ca_type: private
      cluster_name: cluster-rke2
      k8s_version_to_provision: v1.24.8+rke2r1
      machine_type: n2-standard-16
      rancher_channel: ${{ inputs.rancher_channel }}
      rancher_version: ${{ inputs.rancher_version }}
      runner_template: elemental-e2e-ci-runner-spot-x86-64-template-n2-standard-16-v2
      test_type: ui
      upgrade_operator: ${{ inputs.upgrade_operator }}
