# This workflow calls the master E2E workflow with custom variables
name: Elemental UI End-To-End tests with Rancher Manager

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

concurrency:
  group: ui-e2e-tests-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: false

jobs:
  ui-e2e-k3s:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      cluster_name: cluster-k3s
      k8s_version_to_provision: v1.24.7+k3s1
      ca_type: selfsigned
      rancher_channel: latest
      rancher_version: devel
      runner: elemental-e2e-ci-runner-spot-x86-64-1
      start_condition: success
      test_type: ui
      zone: us-central1-a
      workflow_download: build-ci.yaml
  ui-e2e-rke2:
    if: always()
    needs: ui-e2e-k3s
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      cluster_name: cluster-rke2
      k8s_version_to_provision: v1.24.7+rke2r1
      ca_type: selfsigned
      rancher_channel: latest
      rancher_version: devel
      runner: elemental-e2e-ci-runner-spot-x86-64-1
      start_condition: success
      test_type: ui
      zone: us-central1-a
      workflow_download: build-ci.yaml
