name: Elemental UI End-To-End tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  ui-e2e-tests:
    runs-on: ui-e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install K3s / Helm / Rancher
        id: installation
        env:
          KUBECONFIG: /etc/rancher/k3s/k3s.yaml
          HELM_VERSION: 3.7.0
          K3S_VERSION: v1.23.9+k3s1
          DASHBOARD_VERSION: elemental-dev
        run: |
          ## Export information
          ETH_DEV=$(ip route | awk '/default via / { print $5 }')
          MY_IP=$(ip a s ${ETH_DEV} | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d' ' -f2)
          export MY_HOSTNAME=$(hostname).prairie.suse.net
          echo '::set-output name=MY_IP::'${MY_IP}
          echo '::set-output name=MY_HOSTNAME::'${MY_HOSTNAME}
          make prepare-ui-e2e-ci

      - name: Start Cypress tests
        env:
          BROWSER: chrome
          CYPRESS_DOCKER: 'cypress/included:9.7.0'
          RANCHER_PASSWORD: rancherpassword
          RANCHER_URL: https://${{ steps.installation.outputs.MY_HOSTNAME }}/dashboard
          RANCHER_USER: admin
          SPEC: |
            cypress/integration/unit_tests/first_connection.spec.ts
            cypress/integration/unit_tests/menu.spec.ts
            cypress/integration/unit_tests/machine_registration.spec.ts

        run: |
          make start-cypress-tests

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7

      # Test run video was always captured, so this action uses "always()" condition
      - name: Upload Cypress videos
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          retention-days: 7

      - name: Delete k3s cluster
        if: always()
        run: |
          make clean-k3s

      - name: Clean all
        if: always()
        uses: colpal/actions-clean@v1
